#!/usr/bin/env bash

set -e

#MISE alias="r"
#MISE description="Run a specific day"

#USAGE flag "--year <year>" help="Year to build for"
#USAGE flag "--day <day>" help="Day to build for"

if [ -z "$usage_day" ]; then
    usage_day=$(date +%d)
fi

if [ -z "$usage_year" ]; then
    usage_year=$(date +%Y)
fi

day=$(printf %02d "$usage_day")

cd "$usage_year"/day"$day"/

go run main.go
